name: Build and Publish NuGet

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      run: |
        echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin" >> $GITHUB_PATH

    - name: Build with MSBuild
      run: |
        & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" DbfLibrary\DbfLibrary.csproj /p:Configuration=Release /p:Platform="Any CPU"

    - name: Display directory structure
      run: tree /f /a

    - name: Pack
      run: nuget pack DbfLibrary\DbfLibrary.csproj -Properties Configuration=Release -OutputDirectory out

    - name: Push NuGet package
      run: dotnet nuget push out/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
